service: aws-node-project

provider:
  name: aws
  runtime: nodejs14.x
        
functions:
  hello:
    handler: src/helloworld/handler.hello
    events:
      - http:
          path: hello
          method: get
